name       : libshout
version    : 2.4.3
release    : 5
source     :
    - https://ftp.osuosl.org/pub/xiph/releases/libshout/libshout-2.4.3.tar.gz : 0d8af55d1141bf90710bcd41a768c9cc5adb251502a0af1dd22c8da215d40dfe
homepage   : https://gitlab.xiph.org/xiph/icecast-libshout/
license    : LGPL-2.0-only
component  : multimedia.library
summary    : Library which can be used to write a source client like ices
description: |
    Library which can be used to write a source client like ices (for icecast)
builddeps  :
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
setup      : |
    %configure --disable-examples --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
