name        : libshout
version     : 2.4.1
release     : 2
source      :
    - http://downloads.xiph.org/releases/libshout/libshout-2.4.1.tar.gz : f3acb8dec26f2dbf6df778888e0e429a4ce9378a9d461b02a7ccbf2991bbf24d
homepage    : http://icecast.org/
license     : GPL-2.0
summary     : Library which can be used to write a source client like ices
builddeps   :
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
description : |
    Library which can be used to write a source client like ices (for icecast)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
